# Generated by Django 4.1.1 on 2024-12-09 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_alter_contract_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 8, 19, 42, 37, 859162, tzinfo=datetime.timezone.utc)),
        ),
    ]
